feat: Дипломный проект - основной функционал
AlexeyMurenkov/java-explore-with-me pull request #1
Opened 2022-11-08 22:50 UTC by AlexeyMurenkov

Основной функционал дипломного проекта в соответствии с ТЗ

2022-11-09 20:29 UTC, EvgenyKoptubenko commented on service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +    public CategoryDto create(@RequestBody @Validated(Create.class) @NotNull CategoryDto categoryDto) {
Нужно добавить логирование по всему проекту

2022-11-09 20:35 UTC, EvgenyKoptubenko commented on service/src/main/java/ru/practicum/ewm/common/exception/ErrorHandler.java
> +    public ApiError handleForbiddenException(ServletException e) {
методы можно объединить, чтобы один метод был для обработки сразу нескольких эксепшенов

2022-11-09 20:40 UTC, EvgenyKoptubenko commented on service/src/main/resources/application.properties
> +spring.datasource.driver-class-name=org.postgresql.Driver
Попробуй разделить конфигурации по профилям. Сейчас одновременно и h2 и postgres.
Если попробовать запустить проект локально, то он падает Caused by: java.net.UnknownHostException: ewm-db

2022-11-09 20:42 UTC, EvgenyKoptubenko commented on stat/src/main/java/ru/practicum/ewm/StatServiceMain.java
> +        SpringApplication.run(StatServiceMain.class, args);
При запуске возникает ошибка Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

2022-11-09 22:12 UTC, AlexeyMurenkov commented on service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +    public CategoryDto create(@RequestBody @Validated(Create.class) @NotNull CategoryDto categoryDto) {
Добавлено логирование всех методов контроллеров основного сервиса и сервиса статистики.

2022-11-09 22:21 UTC, AlexeyMurenkov commented on service/src/main/java/ru/practicum/ewm/common/exception/ErrorHandler.java
> +    public ApiError handleForbiddenException(ServletException e) {
Объединены в один метод обработчики исключений, возвращающие одинаковый  статус и имеющие одинаковую логику формирования ApiError

2022-11-09 22:42 UTC, AlexeyMurenkov commented on service/src/main/resources/application.properties
> +spring.datasource.driver-class-name=org.postgresql.Driver
Изменены настройки конфигурации  таким образом, что при запуске в докере сервисы запускаются с драйвером postgresql, а при локальном запуске из ide - с драйвером H2 с БД в RAM.

2022-11-09 22:50 UTC, AlexeyMurenkov commented on stat/src/main/java/ru/practicum/ewm/StatServiceMain.java
> +        SpringApplication.run(StatServiceMain.class, args);
Изменены настройки application.properties для основного сервера и сервера статистики

2022-11-09 22:53 UTC, AlexeyMurenkov commented
> Предлагаю сделать разделение конфигурации локального запуска и для запуска на сервере. Сделай так же инструкцию как запустить проект локально. В идеале запускаться должно по одной кнопке без каких-то изменений в настройках, без установки базы данных отдельно. Все должно подняться по нажатию на одну-две кнопки

Изменены настройки так, что локально из ide сервисы запускаются стандартным способом с драйвером H2. Сначала нужно запускать сервер статистики, а потом основной сервис.

2022-11-10 19:14 UTC, EvgenyKoptubenko commented on README.md
> +https://github.com/AlexeyMurenkov/java-explore-with-me/pull/1
В readme должно быть описание проекта: что он делает, как его запускать, желательно еще диаграмма базы данных или ссылка на архитектурный документ

2022-11-10 19:19 UTC, EvgenyKoptubenko commented on service/src/main/java/ru/practicum/ewm/common/exception/ErrorHandler.java
> +    public ApiError handleHttpMessageConversionException(Exception e) {
Можно объединить с методом handleMethodArgumentNotValidException https://www.baeldung.com/exception-handling-for-rest-with-spring

2022-11-10 19:19 UTC, EvgenyKoptubenko requested changes
Замечаний почти нет. По сути две - Advice и стектрейс при неверном запросе.
Еще внизу All checks have failed
1 failing check - нужно, чтобы все тесты проходили

2022-11-10 19:24 UTC, AlexeyMurenkov commented on service/src/main/java/ru/practicum/ewm/user/controller/AdminUserController.java
> +    public UserDto create(@RequestBody @Valid @NotNull UserDto userDto) {
Исправлено. Теперь в ответе при исключении видны только стандартные сообщения об ошибке.

2022-11-10 19:24 UTC, AlexeyMurenkov commented on service/src/main/java/ru/practicum/ewm/common/exception/ErrorHandler.java
> +    public ApiError handleHttpMessageConversionException(Exception e) {
Готово

2022-11-10 20:13 UTC, AlexeyMurenkov commented
> Замечаний почти нет. По сути две - Advice и стектрейс при неверном запросе. Еще внизу All checks have failed 1 failing check - нужно, чтобы все тесты проходили

Готово

2022-11-11 17:45 UTC, merged